"use client";
import React from "react";
import { ShieldCheck, Warning, Siren, CheckCircle, Info } from "@phosphor-icons/react";

const tasks = [
  { metric: "HIPAA Audits Failed", val: "0", desc: "Last 30 Days", status: "good" },
  { metric: "Access Log Anomalies", val: "3", desc: "Needs Review", status: "warning" },
  { metric: "Data Encryption Rate", val: "100%", desc: "At Rest & Transit", status: "good" },
  { metric: "Staff Training Due", val: "14", desc: "Overdue by 7 days", status: "critical" },
];

export default function AdminCompliancePage() {
  return (
    <div>
      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start", marginBottom: 24 }}>
        <div>
          <h1 className="heading-lg" style={{ display: "inline-flex", alignItems: "center", gap: "8px" }}>
            <ShieldCheck size={28} weight="duotone" /> Compliance & Security
          </h1>
          <p className="text-muted" style={{marginTop:4}}>HIPAA compliance, audits, and security metrics</p>
        </div>
        <button className="btn btn-primary">Generate Audit Report</button>
      </div>

      <div style={{ display: "grid", gridTemplateColumns: "repeat(4, 1fr)", gap: 16, marginBottom: 24 }}>
        {tasks.map((t,i) => (
          <div key={i} className="card" style={{ padding: 20 }}>
            <span className="text-sm text-muted">{t.metric}</span>
            <div style={{ fontSize: "2rem", fontWeight: 800, fontFamily: "var(--font-mono)", marginTop: 8, color: t.status==="good"?"var(--accent)":t.status==="warning"?"var(--warning)":"var(--critical)" }}>{t.val}</div>
            <span className="text-xs text-muted">{t.desc}</span>
          </div>
        ))}
      </div>

      <div className="card" style={{ padding: 24 }}>
        <h3 className="heading-md" style={{ marginBottom: 16 }}>Recent Security Events</h3>
        <div style={{ display: "flex", flexDirection: "column", gap: 8 }}>
          {[
            { msg: "Multiple failed login attempts detected for user USR-045", time: "2 hours ago", type: "warning", icon: <Warning size={18} weight="duotone" style={{ color: "var(--warning)" }} /> },
            { msg: "PHI export generated by Admin Tom Hayes", time: "5 hours ago", type: "info", icon: <Info size={18} weight="duotone" style={{ color: "var(--primary)" }} /> },
            { msg: "Automated database backup completed successfully", time: "1 day ago", type: "success", icon: <CheckCircle size={18} weight="duotone" style={{ color: "var(--accent)" }} /> },
            { msg: "API Key rotation required for EHR Gateway", time: "2 days ago", type: "critical", icon: <Siren size={18} weight="duotone" style={{ color: "var(--critical)" }} /> },
          ].map((e,i) => (
            <div key={i} style={{ padding: 12, borderRadius: 6, display: "flex", alignItems: "center", gap: 12, background: e.type==="warning"?"var(--warning-glow)":e.type==="critical"?"var(--critical-glow)":"var(--bg-tertiary)" }}>
              <span style={{ display: "inline-flex", alignItems: "center" }}>{e.icon}</span>
              <div style={{ flex: 1, fontSize: "0.875rem" }}>{e.msg}</div>
              <span className="text-xs text-muted">{e.time}</span>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
